import { chromium } from 'playwright';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext();
await context.route(/facebook|clarity|google-analytics|googletagmanager|breeze.in|shopify-speed|aov-offer|standard-actions|web-pixels|trekkie|shopify-perf/,r=>r.abort());
const page=await context.newPage();await page.setViewportSize({width:1440,height:1000});
await page.goto('https://oakandlily.in/',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(2500);
await page.evaluate(()=>{document.querySelectorAll('video').forEach(v=>v.pause());document.querySelectorAll('.scroll-trigger').forEach(e=>e.classList.remove('scroll-trigger--offscreen'));});await page.screenshot({timeout:120000,path:'qa/reference-desktop.png',fullPage:true});
await fs.writeFile('qa/reference-inspection.json',JSON.stringify(await page.evaluate(()=>({title:document.title,sections:[...document.querySelectorAll('main > *')].map(e=>({id:e.id,box:e.getBoundingClientRect().toJSON(),text:e.innerText?.slice(0,100)})),header:getComputedStyle(document.querySelector('header')).cssText,colors:[...document.querySelectorAll('h2,header,.announcement-bar')].map(e=>({selector:e.className,font:getComputedStyle(e).font,color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}))})),null,2));
await page.setViewportSize({width:390,height:844});await page.goto('https://oakandlily.in/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(2000);await page.evaluate(()=>{document.querySelectorAll('video').forEach(v=>v.pause());document.querySelectorAll('.scroll-trigger').forEach(e=>e.classList.remove('scroll-trigger--offscreen'));});await page.screenshot({timeout:120000,path:'qa/reference-mobile.png',fullPage:true});
await page.locator('header-drawer summary').first().click();await page.waitForTimeout(500);await page.evaluate(()=>{document.querySelectorAll('video').forEach(v=>v.pause());document.querySelectorAll('.scroll-trigger').forEach(e=>e.classList.remove('scroll-trigger--offscreen'));});await page.screenshot({timeout:120000,path:'qa/reference-menu.png'});
for(const [name,path] of [['collection','/collections/kitchen-napkins'],['product','/products/peach-pink-kitchen-napkins'],['story','/pages/our-story']]) {await page.setViewportSize({width:1440,height:1000});await page.goto('https://oakandlily.in'+path,{waitUntil:'domcontentloaded'});await page.waitForTimeout(1800);await page.evaluate(()=>{document.querySelectorAll('video').forEach(v=>v.pause());document.querySelectorAll('.scroll-trigger').forEach(e=>e.classList.remove('scroll-trigger--offscreen'));});await page.screenshot({timeout:120000,path:`qa/reference-${name}.png`,fullPage:true});}
await browser.close();
